edition = "2021"
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
imports_granularity = "Crate"
reorder_impl_items = true
unstable_features = true
use_field_init_shorthand = true
