style_edition = "2024"
format_macro_matchers = true
format_strings = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_impl_items = true
unstable_features = true
use_field_init_shorthand = true
format_code_in_doc_comments = true