// ANCHOR: Deref
use deriving_via::DerivingVia;

#[derive(DerivingVia)]
#[deriving(From)]
pub struct Inner(i32);

#[derive(DerivingVia)]
#[deriving(From)]
// Deref is implicitly generated by DerivingVia for the newtype pattern
pub struct Wrapper(Inner);

pub fn main() {
    let wrapper = Wrapper(Inner(42));
    // We can call i32 methods through Deref coercion
    let _ = wrapper.to_string();
}
// ANCHOR_END: Deref

#[test]
fn test_main() {
    main();
}
