[package]
name = "examples"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false
description = "DerivingVia examples"

[dependencies]
deriving_via = { version = "=2.3.1", path = "../deriving_via" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies.cargo-husky]
version = "1.5.0"
default-features = false
features = ["user-hooks"]

[package.metadata.cargo-udeps.ignore]
development = ["cargo-husky"]
