[package]
name = "deriving_via_macros"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "DerivingViaMacros"

[package.metadata.release]
disable-tag = true

[lib]
proc-macro = true

[dependencies]
deriving-via-impl = { version = "2.2.0", path = "../deriving_via_impl" }
itertools = "0.15.0"
quote = { workspace = true }
proc-macro2 = "1.0.107"
strum = "0.28.0"
strum_macros = "0.28.0"
syn = { workspace = true }

[dev-dependencies.cargo-husky]
version = "1.5.0"
default-features = false # Disable features which are enabled by default
features = ["user-hooks"]

[package.metadata.cargo-udeps.ignore]
development = ["cargo-husky"]
