[package]
name = "test_suite"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
deriving_via = { path = "../deriving_via" }
serde = "1.0.171"
serde_json = "1.0.100"

[dev-dependencies]
automod = "1.0.14"
