name: Security Audit
on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read
  checks: write
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
